dumps:
  path: /mnt/hdd1/amirassov/cft
  weights: weights
  logs: logs

data:
  path: /home/amirassov/cft/data/
  src_train: src_fullname.txt
  tgt_train: tgt_fullname.txt
  src_test: src_fullname_val.txt
  tgt_test: tgt_fullname_val.txt
  pre_test: pre_fullname_val.txt
